# Generated by Django 4.2.25 on 2026-03-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADOrganizationalUnitLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=1024)),
                ('distinguished_name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'AD Organizational Unit Limiter',
                'verbose_name_plural': 'AD Organizational Unit Limiters',
            },
        ),
        migrations.CreateModel(
            name='ADStaffSyncGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('distinguished_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('members', models.ManyToManyField(related_name='ad_group_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Staff API Permission (Django Data Model is ADStaffSyncGroup)',
                'verbose_name_plural': 'IT Staff API Permissions',
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('page_url', models.URLField(blank=True, default='', max_length=2048)),
                ('page_path', models.CharField(blank=True, default='', max_length=512)),
                ('site_domain', models.CharField(blank=True, default='', max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug report',
                'verbose_name_plural': 'Bug reports',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='MFAResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('performed_by_username', models.CharField(blank=True, max_length=150)),
                ('target_user_principal_name', models.EmailField(max_length=255)),
                ('reset_type', models.CharField(choices=[('individual', 'Individual'), ('bulk', 'Bulk')], max_length=32)),
                ('was_successful', models.BooleanField(default=False)),
                ('method_id', models.CharField(blank=True, max_length=255)),
                ('method_type', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_reset_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA reset attempt',
                'verbose_name_plural': 'MFA reset attempts',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('api_request', 'API request')], max_length=32)),
                ('was_successful', models.BooleanField(default=False)),
                ('request_method', models.CharField(blank=True, max_length=16)),
                ('request_path', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User activity log entry',
                'verbose_name_plural': 'User activity log entries',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='MFAResetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('performed_by_username', models.CharField(blank=True, max_length=150)),
                ('performed_by_display_name', models.CharField(blank=True, max_length=255)),
                ('performed_by_user_principal_name', models.EmailField(blank=True, max_length=255)),
                ('target_user_principal_name', models.EmailField(max_length=255)),
                ('reset_type', models.CharField(choices=[('individual', 'Individual'), ('bulk', 'Bulk')], max_length=32)),
                ('was_successful', models.BooleanField(default=False)),
                ('client_label', models.CharField(blank=True, max_length=255)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_records', to='myview.mfaresetattempt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_reset_records', to='myview.adorganizationalunitlimiter')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_reset_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA reset record',
                'verbose_name_plural': 'MFA reset records',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='LimiterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['iplimiter', 'adorganizationalunitlimiter']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='IPLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('ad_groups', models.ManyToManyField(blank=True, related_name='ip_limiters', to='myview.adstaffsyncgroup')),
            ],
            options={
                'verbose_name': 'IP Limiter',
                'verbose_name_plural': 'IP Limiters',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(blank=True, default='', max_length=6)),
                ('ad_groups', models.ManyToManyField(blank=True, related_name='endpoints', to='myview.adstaffsyncgroup')),
                ('limiter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myview.limitertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=myview.models.bug_report_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='myview.bugreport')),
            ],
            options={
                'verbose_name': 'Bug report attachment',
                'verbose_name_plural': 'Bug report attachments',
                'ordering': ['datetime_created'],
            },
        ),
        migrations.AddField(
            model_name='adorganizationalunitlimiter',
            name='ad_groups',
            field=models.ManyToManyField(blank=True, related_name='ad_organizational_unit_limiters', to='myview.adstaffsyncgroup'),
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('user_principal_name', models.CharField(blank=True, default='', max_length=255)),
                ('auth_method', models.CharField(default='msal', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User login',
                'verbose_name_plural': 'User logins',
                'ordering': ['-datetime_created'],
                'indexes': [models.Index(fields=['datetime_created'], name='myview_user_datetim_e42a3d_idx'), models.Index(fields=['user_principal_name'], name='myview_user_user_pr_6a4aeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('query_string', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('auth_type', models.CharField(blank=True, default='', max_length=32)),
                ('auth_token', models.CharField(blank=True, default='', max_length=128)),
                ('action', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API request log',
                'verbose_name_plural': 'API request logs',
                'ordering': ['-datetime_created'],
                'indexes': [models.Index(fields=['datetime_created'], name='myview_apir_datetim_b8c2a6_idx'), models.Index(fields=['path'], name='myview_apir_path_f5c028_idx'), models.Index(fields=['status_code'], name='myview_apir_status__e3c9d0_idx')],
            },
        ),
    ]
