# Generated by Django 4.2.25 on 2026-03-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adstaffsyncgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bugreportattachment',
            name='bug_report',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='ad_groups',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='limiter_type',
        ),
        migrations.RemoveField(
            model_name='iplimiter',
            name='ad_groups',
        ),
        migrations.RemoveField(
            model_name='limitertype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mfaresetrecord',
            name='client',
        ),
        migrations.DeleteModel(
            name='ADOrganizationalUnitLimiter',
        ),
        migrations.DeleteModel(
            name='ADStaffSyncGroup',
        ),
        migrations.DeleteModel(
            name='BugReport',
        ),
        migrations.DeleteModel(
            name='BugReportAttachment',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='IPLimiter',
        ),
        migrations.DeleteModel(
            name='LimiterType',
        ),
    ]
