# Generated by Django 4.2.25 on 2025-12-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descriptive_name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('target_ous', models.JSONField(blank=True, default=list, help_text='List of distinguished names that fall under this unit.')),
                ('ledelsesrepresentanter', models.JSONField(blank=True, default=list, help_text='Management representatives responsible for the unit.')),
                ('contact_emails', models.JSONField(blank=True, default=list, help_text='Generic contact addresses for the unit.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'organizational unit profile',
                'verbose_name_plural': 'organizational unit profiles',
                'ordering': ['descriptive_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='Optional short identifier used inside Defender dashboards.', max_length=64)),
                ('primary_contact_email', models.EmailField(blank=True, help_text='Primary mailbox for the system owner.', max_length=254)),
                ('additional_contact_emails', models.JSONField(blank=True, default=list, help_text='Extra recipients that should be notified about alerts.')),
                ('notes', models.TextField(blank=True)),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_owners', to='defender.organizationalunitprofile')),
            ],
            options={
                'verbose_name': 'system owner',
                'verbose_name_plural': 'system owners',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(help_text='IPv4/IPv6 address or CIDR (e.g. 192.0.2.0/24).', max_length=64, unique=True)),
                ('ip_version', models.PositiveSmallIntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], editable=False)),
                ('prefix_length', models.PositiveSmallIntegerField(editable=False)),
                ('network_address', models.CharField(editable=False, max_length=64)),
                ('system_name', models.CharField(blank=True, help_text='Free-form label for the system that uses this network.', max_length=255)),
                ('system_description', models.TextField(blank=True)),
                ('delegated_by_name', models.CharField(blank=True, max_length=255)),
                ('delegated_by_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_assignments', to='defender.systemowner')),
            ],
            options={
                'verbose_name': 'network ownership',
                'verbose_name_plural': 'network ownerships',
                'ordering': ['network'],
            },
        ),
        migrations.AddConstraint(
            model_name='systemowner',
            constraint=models.UniqueConstraint(condition=models.Q(('short_code', ''), _negated=True), fields=('short_code',), name='unique_non_empty_owner_short_code'),
        ),
        migrations.AddIndex(
            model_name='networkownership',
            index=models.Index(fields=['owner', 'ip_version'], name='defender_ne_owner_i_353066_idx'),
        ),
    ]
