# Generated by Django 4.2.25 on 2025-12-15 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnitDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('staff_title', models.CharField(blank=True, max_length=255)),
                ('distinguished_name', models.CharField(blank=True, max_length=512)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='defender.organizationalunitprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_unit_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organizational unit delegate',
                'verbose_name_plural': 'organizational unit delegates',
                'ordering': ['organizational_unit__descriptive_name', 'email'],
                'unique_together': {('organizational_unit', 'email')},
            },
        ),
    ]
