# Generated by Django 4.2.15 on 2025-09-29 13:46

from django.db import migrations, models


def populate_adgroupassociation_names(apps, schema_editor):
    ADGroupAssociation = apps.get_model("myview", "ADGroupAssociation")

    for association in ADGroupAssociation.objects.all():
        canonical_name = association.canonical_name or ""
        segments = [segment for segment in canonical_name.split('/') if segment]
        if segments:
            association.name = segments[-1]
        else:
            association.name = canonical_name
        association.save(update_fields=["name"])


def noop_reverse(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("myview", "0002_chatthread_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adgroupassociation",
            options={
                "verbose_name": "IT Staff API Permission",
                "verbose_name_plural": "IT Staff API Permissions",
            },
        ),
        migrations.AddField(
            model_name="adgroupassociation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(populate_adgroupassociation_names, noop_reverse),
    ]
