# Generated by Django 4.2.15 on 2025-10-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myview", "0003_alter_adgroupassociation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("login", "Login"), ("api_request", "API request")],
                        max_length=32,
                    ),
                ),
                ("was_successful", models.BooleanField(default=False)),
                ("request_method", models.CharField(blank=True, max_length=16)),
                ("request_path", models.CharField(blank=True, max_length=512)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User activity log entry",
                "verbose_name_plural": "User activity log entries",
                "ordering": ["-datetime_created"],
            },
        ),
    ]
