# Generated by Django 4.2.15 on 2025-10-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


TABLE_NAME = "myview_userloginlog"


def _get_model(apps, model_name):
    """Return the historical model or fall back to the runtime model."""

    try:
        return apps.get_model("myview", model_name)
    except LookupError:
        from myview import models as myview_models

        return getattr(myview_models, model_name)


def create_userloginlog_table(apps, schema_editor):
    if TABLE_NAME in schema_editor.connection.introspection.table_names():
        return

    UserLoginLog = _get_model(apps, "UserLoginLog")
    schema_editor.create_model(UserLoginLog)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myview', '0005_apirequestlog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserLoginLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('datetime_created', models.DateTimeField(auto_now_add=True)),
                        ('datetime_modified', models.DateTimeField(auto_now=True)),
                        ('user_principal_name', models.CharField(blank=True, default='', max_length=255)),
                        ('auth_method', models.CharField(default='msal', max_length=32)),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                        ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                        ('session_key', models.CharField(blank=True, default='', max_length=40)),
                        ('additional_info', models.JSONField(blank=True, null=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'User login',
                        'verbose_name_plural': 'User logins',
                        'ordering': ['-datetime_created'],
                        'indexes': [models.Index(fields=['datetime_created'], name='myview_user_datetim_e42a3d_idx'), models.Index(fields=['user_principal_name'], name='myview_user_user_pr_6a4aeb_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_userloginlog_table, migrations.RunPython.noop),
            ],
        ),
    ]
