# Generated by Django 4.2.25 on 2025-10-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myview.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myview", "0006_userloginlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("page_url", models.URLField(blank=True, max_length=2048)),
                ("page_path", models.CharField(blank=True, max_length=512)),
                ("site_domain", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bug_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bug report",
                "verbose_name_plural": "Bug reports",
                "ordering": ["-datetime_created"],
            },
        ),
        migrations.CreateModel(
            name="BugReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=myview.models.bug_report_attachment_upload_to
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "bug_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="myview.bugreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bug report attachment",
                "verbose_name_plural": "Bug report attachments",
                "ordering": ["datetime_created"],
            },
        ),
    ]
