# Generated by Django 4.2.25 on 2025-10-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myview", "0007_bugreport_bugreportattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAResetAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("performed_by_username", models.CharField(blank=True, max_length=150)),
                ("target_user_principal_name", models.EmailField(max_length=255)),
                ("method_id", models.CharField(blank=True, max_length=255)),
                ("method_type", models.CharField(blank=True, max_length=255)),
                ("was_successful", models.BooleanField(default=False)),
                (
                    "reset_type",
                    models.CharField(
                        choices=[
                            ("bulk", "Bulk reset"),
                            ("individual", "Individual reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_reset_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA reset attempt",
                "verbose_name_plural": "MFA reset attempts",
                "ordering": ["-datetime_created"],
            },
        ),
    ]
