# Generated by Django 4.2.25 on 2025-10-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myview", "0008_mfaresetattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAResetRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("performed_by_username", models.CharField(blank=True, max_length=150)),
                (
                    "performed_by_display_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "performed_by_user_principal_name",
                    models.EmailField(blank=True, max_length=255),
                ),
                ("target_user_principal_name", models.EmailField(max_length=255)),
                (
                    "reset_type",
                    models.CharField(
                        choices=[
                            ("bulk", "Bulk reset"),
                            ("individual", "Individual reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("was_successful", models.BooleanField(default=False)),
                ("client_label", models.CharField(blank=True, max_length=255)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reset_records",
                        to="myview.mfaresetattempt",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_reset_records",
                        to="myview.adorganizationalunitlimiter",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_reset_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA reset record",
                "verbose_name_plural": "MFA reset records",
                "ordering": ["-datetime_created"],
            },
        ),
    ]
