"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
import sys
import warnings
from urllib.parse import urlparse

# Load .env file
from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _as_bool(value: str | None, default: bool) -> bool:
    """Return a boolean value for environment variables."""

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def _as_float(value: str | None, default: float, *, minimum: float | None = None) -> float:
    """Return a float parsed from an environment variable with sensible defaults."""

    if value is None:
        result = default
    else:
        try:
            result = float(value)
        except (TypeError, ValueError):
            result = default

    if minimum is not None and result < minimum:
        return minimum
    return result


def _split_env_list(value: str | None) -> list[str]:
    """Split an environment variable into a list of non-empty strings."""

    if not value:
        return []

    separators = [';', ',']
    for separator in separators:
        value = value.replace(separator, '\n')

    return [item.strip() for item in value.splitlines() if item.strip()]


PROJECT_ROOT = BASE_DIR.parent


def _ensure_storage_dir(
    env_var_name: str,
    *,
    default_path: Path,
    fallback_path: Path,
    description: str,
) -> str:
    """Return a writable directory for static/media storage.

    The function attempts the environment-provided path (if any) followed by the
    default path. If neither of those are writable, a project-local fallback is
    used. This prevents collectstatic from failing in read-only environments.
    """

    candidate_paths: list[Path] = []

    env_value = os.getenv(env_var_name)
    if env_value:
        candidate_paths.append(Path(env_value))

    for path in (default_path, fallback_path):
        if path not in candidate_paths:
            candidate_paths.append(path)

    for path in candidate_paths:
        try:
            path.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            warnings.warn(
                f"Unable to use {description} directory '{path}': {exc}",
                stacklevel=2,
            )
            continue

        if os.access(path, os.W_OK):
            return str(path)

        warnings.warn(
            f"Unable to use {description} directory '{path}': directory is not writable.",
            stacklevel=2,
        )

    raise ImproperlyConfigured(
        f"No writable {description} directory configured via {env_var_name}."
    )

custom_env_file = os.getenv("DJANGO_ENV_FILE") or os.getenv("APP_ENV_FILE")
candidate_env_paths = []

if custom_env_file:
    custom_env_path = Path(custom_env_file)
    if not custom_env_path.is_absolute():
        custom_env_path = PROJECT_ROOT / custom_env_path
    candidate_env_paths.append(custom_env_path)

candidate_env_paths.extend(
    [
        PROJECT_ROOT / ".env",
        PROJECT_ROOT / ".devcontainer" / ".env",
        PROJECT_ROOT.parent / ".devcontainer" / ".env",
    ]
)

for env_path in candidate_env_paths:
    if env_path and env_path.exists():
        load_dotenv(dotenv_path=env_path, override=True)
        break
else:
    # Fall back to standard .env discovery (no-op if the file does not exist).
    load_dotenv(override=True)

# settings.py

# AD group cache timeout (seconds). Default: 15 minutes
try:
    AD_GROUP_CACHE_TIMEOUT = int(os.getenv('AD_GROUP_CACHE_TIMEOUT', str(15 * 60)))
except ValueError:
    AD_GROUP_CACHE_TIMEOUT = 15 * 60

default_group_sync_bases = _split_env_list(os.getenv('AD_GROUP_SYNC_BASE_DNS'))
if not default_group_sync_bases:
    default_group_sync_bases = [
        'OU=API-SECURITY-AIT-DTU-DK,OU=Groups,OU=SOC,OU=CIS,OU=AIT,DC=win,DC=dtu,DC=dk',
    ]

AD_GROUP_SYNC_BASE_DNS = tuple(default_group_sync_bases)
AD_GROUP_SYNC_DELETE_MISSING = _as_bool(os.getenv('AD_GROUP_SYNC_DELETE_MISSING'), True)
AD_GROUP_AUTO_SYNC_ENABLED = _as_bool(os.getenv('AD_GROUP_AUTO_SYNC_ENABLED'), False)
AD_GROUP_SYNC_REFRESH_MEMBERS = _as_bool(os.getenv('AD_GROUP_SYNC_REFRESH_MEMBERS'), False)

default_mfa_reset_group_prefixes = _split_env_list(
    os.getenv("MFA_RESET_GROUP_CANONICAL_PREFIXES")
)
if not default_mfa_reset_group_prefixes:
    default_mfa_reset_group_prefixes = [
        "win.dtu.dk/AIT/CIS/SOC/Groups/API-SECURITY-AIT-DTU-DK",
    ]

MFA_RESET_GROUP_CANONICAL_PREFIXES = tuple(default_mfa_reset_group_prefixes)

default_ou_limiter_bases = _split_env_list(os.getenv('AD_OU_LIMITER_BASES'))
if not default_ou_limiter_bases:
    default_ou_limiter_bases = ['win.dtu.dk/DTUBaseUsers']

AD_OU_LIMITER_BASES = tuple(default_ou_limiter_bases)
AD_OU_LIMITER_DELETE_MISSING = _as_bool(os.getenv('AD_OU_LIMITER_DELETE_MISSING'), True)

MFA_RESET_ADMINS_BASE_DN = os.getenv(
    "MFA_RESET_ADMINS_BASE_DN",
    "OU=MFAResetAdmins,OU=Groups,OU=SOC,OU=CIS,OU=AIT,DC=win,DC=dtu,DC=dk",
)



# SECURITY WARNING: keep the secret key used in production secret!
secret_key = os.getenv('DJANGO_SECRET')
if not secret_key:
    raise ImproperlyConfigured("DJANGO_SECRET must be set.")
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _as_bool(os.getenv("DJANGO_DEBUG"), False)


# Sets the admin path from .env
admin_url_path = os.getenv("DJANGO_ADMIN_URL")
if not admin_url_path:
    raise ImproperlyConfigured("DJANGO_ADMIN_URL must be set.")
ADMIN_URL_PATH = admin_url_path.strip("/") + "/"

# Allowed hosts for the Django APP
allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS')


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_SESSION_COOKIE_SECURE'), True)
CSRF_COOKIE_SECURE = _as_bool(os.getenv('DJANGO_CSRF_COOKIE_SECURE'), True)
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '3600'))  # This sets the duration for one hour, adjust as needed.
SECURE_HSTS_INCLUDE_SUBDOMAINS = _as_bool(os.getenv('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS'), True)
SECURE_HSTS_PRELOAD = _as_bool(os.getenv('DJANGO_SECURE_HSTS_PRELOAD'), True)
SECURE_SSL_REDIRECT = _as_bool(os.getenv('DJANGO_SECURE_SSL_REDIRECT'), False)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    # 'drf_yasg', # Swagger
    'myview',
    'active_directory',
    'graph',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Serves static files (Alternativ to Nginx-for-static-files). Chat says this needs to be right after 'django.middleware.security.SecurityMiddleware'
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myview.middleware.AccessControlMiddleware', # My own middleware the defines which users can access what
]

# Root of all websites (app's) urls. located app ./app/urls.py
ROOT_URLCONF = 'app.urls'

# Sets the page template renderer, and where they are located. They are located under project/templates/ .e.g myview/templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Located at the project 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # required for admin
                'django.contrib.auth.context_processors.auth',  # REQUIRED for your error
                'django.contrib.messages.context_processors.messages',
            ],
        }
    }
]

# Language and timezone
USE_TZ = True  # Django stores time in UTC internally. But if USE_TZ is set to True, the time is presentented locally
TIME_ZONE = 'Europe/Copenhagen' #
LANGUAGE_CODE = 'da-dk'

# If the field 'id' is not defined in a model, then this will be the default type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'