# Generated by Django 4.2.15 on 2025-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("graph", "Microsoft Graph"),
                            ("defender", "Microsoft Defender"),
                        ],
                        help_text="Identifier for the external service the token authenticates against.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Bearer token returned by the external identity provider."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when the token is no longer valid."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service token",
                "verbose_name_plural": "Service tokens",
            },
        ),
    ]
